# development config
version: '3.7'
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./src:/app/src
      - ./config:/app/config
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/dev
    command: ["yarn", "run", "dev"]
    depends_on:
      - mongodb
    networks:
      - bg-net
  mongodb:
    image: 'mongo:4.2.2-bionic'
    networks:
      - bg-net
    volumes:
      - mongodb-data:/data/db
networks:
  bg-net:
volumes:
  mongodb-data: